MyDjangoBlog/urls.py
#!/usr/bin/env python
# coding=utf-8
"""MyDjangoBlog URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url 接收4个参数 regex view kwargs name
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
]

blog/urls.py
#!/usr/bin/env python
# coding=utf-8
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

blog/models.py
#!/usr/bin/env python
# coding=utf-8
from __future__ import unicode_literals

from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')


class Choice(models.Model):
    question = models.ForeignKey(Question)               # 外键
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

blog/views.py
#!/usr/bin/env python
# coding=utf-8
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.core.urlresolvers import reverse
from django.views import generic

from .models import Choice, Question

# 视图的作用 1) 返回 HttpResponse 对象 2）抛出异常
# 模板填充 1)from django.template import loader
#           template = loader.get_template('blog/index.html')
#           return HttpResponse(template.render(context, request))
#          2)from django.shortcuts import render
#           return render(request, 'blog/index.html', context)
# 抛出异常  1） from django.http import Http404
#               try:
#                   question = Question.objects.get(pk=question_id)
#               except Question.DoesNotExist:
#                   raise Http404("Question does not exist")
#           2)  from django.shortcuts import get_object_or_404
#               question = get_object_or_404(Question, pk=question_id)
# 数据库读取记录    from .models import Question
#                   1) latest_question_list = Question.objects.order_by('-pub_date')[:5]
#                   2) question = Question.objects.get(pk=question_id)
#                   3) question = Question.objects.filter(pk=question_id)
#                   4) question = get_object_or_404(Question, pk=question_id)
#                   5) question = get_list_or_404(Question, pk=question_id)
class IndexView(generic.ListView):
    template_name = 'blog/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """返回最后发布的5个问题"""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'blog/detail.html'



class ResultsView(generic.DetailView):
    model = Question
    template_name = 'blog/results.html'

def vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)
    try:
        # request.POST['choice'] 以字符串形式返回选择的 Choice 的 ID
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # 重新显示问题的投票表单
        return render(request, 'blog/detail.html', {
            'question': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # 成功处理之后 POST 数据之后，总是返回一个 HttpResponseRedirect 。防止因为用户点击了后退按钮而提交了两次。
        return HttpResponseRedirect(reverse('blog:results', args=(p.id,)))

blog/templates/blog/detail.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}" />

{% comment%}
<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>
{% endcomment %}

<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'blog:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    {# forloop.counter 指示 for 标签已经循环多少次 #}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

blog/templates/blog/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}" />

{% comment %}
    {{ 变量 }}
    {% 标签 %}
    {{ Django|过滤器 }}
    {# 这将不会被渲染 #}
    {# comment #}
    多行注释
    多行注释
    {# endcomment #}
{% endcomment %}

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        {# 硬编码的 href="/polls/{{ question.id }} #}
        {# 在 polls.urls 的 urls() 函数中通过 name 参数为 URL 定义了名字 #}
        {# blog 是 namespace #}
        <li><a href="{% url 'blog:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

blog/templates/blog/results.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}" />

<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'blog:detail' question.id %}">Vote again?</a>